In [15]:
import pandas as pd
import numpy as np
from numpy import array
import matplotlib.pyplot as plt
import math
import openpyxl
from statistics import *

In [16]:
wb = openpyxl.load_workbook('GCData-JGI_TEs.xlsx')
sheet_input = wb['EXT_STD']
numCols = len(sheet_input[1])
# Parses through external standard concentrations from EXT_STD tab and outputs the variables to be copied into below block
i = 0
for row in sheet_input.iter_rows(min_row = 2, max_row = 100, min_col = 1, max_col = numCols):
    # skips first row and starts at 2nd row, which contains ext standard concentrations
    if row[0].value is not None: 
        print(row[0].value + '_area = ' + str([data.value for data in row[2:numCols:2]]))
        print(row[0].value + '_conc = ' + str([data.value for data in row[1:numCols:2]]))
    i = i + 1

C3_area = [3062, 3062, 18877, 18877, 32427, 32427, 231392, 231392, 469104, 469104, 740509, 740509]
C3_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C4_area = [2126, 2126, 12053, 12053, 20414, 20414, 126804, 126804, 241543, 241543, None, None]
C4_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C5_area = [3155, 3155, 17503, 17503, 29701, 29701, 178598, 178598, 337997, 337997, 531610, 531610]
C5_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C6_area = [4485, 4485, 25285, 25285, 42948, 42948, 261472, 261472, 502347, 502347, 804287, 804287]
C6_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C7_area = [5172, 5172, 28764, 28764, 49388, 49388, 297295, 297295, 588810, 588810, 954886, 954886]
C7_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C8_area = [5359, 5359, 30207, 30207, 51426, 51426, 313020, 313020, 618352, 618352, 1019142, 1019142]
C8_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C9_area = [5781, 5781, 32428, 32428, 55544, 55544, 336594, 336594, 670818, 670818, 1099821, 1099821]
C9_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C10_area = [5943, 5943, 32775, 32775, 55959, 55959, 336066, 336066, 658831, 658831, 1089808, 1089808]
C10_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C11_area = [6832, 6832, 34519, 34519, 58710, 58710, 350711, 350711, 682233, 682233, 1119563, 1119563]
C11_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C12_area = [6733, 6733, 36394, 36394, 61907, 61907, 366312, 366312, 707998, 707998, 1149985, 1149985]
C12_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C13_area = [7215, 7215, 38967, 38967, 66346, 66346, 384912, 384912, 729820, 729820, 1179169, 1179169]
C13_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C14_area = [7555, 7555, 39699, 39699, 67376, 67376, 387202, 387202, 723283, 723283, 1173910, 1173910]
C14_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C15_area = [8420, 8420, 41991, 41991, 72272, 72272, 400179, 400179, 742848, 742848, 1178984, 1178984]
C15_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C16_area = [8487, 8487, 39228, 39228, 67762, 67762, 366042, 366042, 677910, 677910, 1083152, 1083152]
C16_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C17_area = [9268, 9268, 38785, 38785, 67421, 67421, 350980, 350980, 644150, 644150, 1024810, 1024810]
C17_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]

In [17]:
### User enters data here, copied from output from above block

#Enter external standard peak areas. Replace individual default_conc if needed
#If any areas are 'None', delte those and their corresponding concentrations


C7_area = [5172, 5172, 28764, 28764, 49388, 49388, 297295, 297295, 588810, 588810, 954886, 954886]
C7_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C8_area = [5359, 5359, 30207, 30207, 51426, 51426, 313020, 313020, 618352, 618352, 1019142, 1019142]
C8_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C9_area = [5781, 5781, 32428, 32428, 55544, 55544, 336594, 336594, 670818, 670818, 1099821, 1099821]
C9_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C10_area = [5943, 5943, 32775, 32775, 55959, 55959, 336066, 336066, 658831, 658831, 1089808, 1089808]
C10_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C11_area = [6832, 6832, 34519, 34519, 58710, 58710, 350711, 350711, 682233, 682233, 1119563, 1119563]
C11_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C12_area = [6733, 6733, 36394, 36394, 61907, 61907, 366312, 366312, 707998, 707998, 1149985, 1149985]
C12_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C13_area = [7215, 7215, 38967, 38967, 66346, 66346, 384912, 384912, 729820, 729820, 1179169, 1179169]
C13_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C14_area = [7555, 7555, 39699, 39699, 67376, 67376, 387202, 387202, 723283, 723283, 1173910, 1173910]
C14_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C15_area = [8420, 8420, 41991, 41991, 72272, 72272, 400179, 400179, 742848, 742848, 1178984, 1178984]
C15_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C16_area = [8487, 8487, 39228, 39228, 67762, 67762, 366042, 366042, 677910, 677910, 1083152, 1083152]
C16_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]
C17_area = [9268, 9268, 38785, 38785, 67421, 67421, 350980, 350980, 644150, 644150, 1024810, 1024810]
C17_conc = [10, 10, 50, 50, 100, 100, 500, 500, 1000, 1000, 2000, 2000]

#Dictionary containing linear slope fit to peak area vs concentration. Add to dictionary if needed.
area_to_conc_scale = {'C7'  : np.polyfit(C7_conc,C7_area,1)[0], 
                      'C8'  : np.polyfit(C8_conc,C8_area,1)[0],
                      'C9'  : np.polyfit(C9_conc,C9_area,1)[0],
                      'C10' : np.polyfit(C10_conc,C10_area,1)[0],
                      'C11' : np.polyfit(C11_conc,C11_area,1)[0],
                      'C12' : np.polyfit(C12_conc,C12_area,1)[0],
                      'C13' : np.polyfit(C13_conc,C13_area,1)[0],
                      'C14' : np.polyfit(C14_conc,C14_area,1)[0],
                      'C15' : np.polyfit(C15_conc,C15_area,1)[0],
                      'C16' : np.polyfit(C16_conc,C16_area,1)[0],
                      'C17' : np.polyfit(C17_conc,C17_area,1)[0],
                      'C18_1' : np.polyfit(C18_1_conc,C18_1_area,1)[0],
                      'C18' : np.polyfit(C18_conc,C18_area,1)[0]}

In [18]:
for x, y in area_to_conc_scale.items():
  print(x, y)

C3 382.131636964
C4 244.327640974
C5 272.035894389
C6 411.339359736
C7 488.391442244
C8 520.453425743
C9 562.174636964
C10 555.891438944
C11 571.060491749
C12 586.901333333
C13 601.104755776
C14 597.39169967
C15 600.347561056
C16 550.522462046
C17 519.944386139

In [21]:
### Enter internal standard concentrations

internalConc = {'C7':50, 'C9':50, 'C11':50, 'C13':50, 'C15':10, 'C17':10}

file = 'GCData-JGI_ACRs.xlsx' #file name
sheet = 'Quantification w IS,ES' #sheet with peak area and chain identification data
area_col = 4 #column number of peak area data (1st column is column 0, 2nd column is column 1, etc.)
chain_col = 5 #column number of chain identification data (1st column is column 0, 2nd column is column 1, etc.)
scale = area_to_conc_scale #dictionary of scale factors to turn area data into concentration data
int_sdt_conc = internalConc #dictionary of internal standard concentrations
saveAs = 'GCData-JGI_ACRs w Conc Data.xlsx' #name to save new file

#New file will be created with name given by the saveAs variable with a new worksheet called "Corrected Concentration"
getData(file, sheet, area_col, chain_col, scale, int_sdt_conc, saveAs)

,0,1,2,3,4,5,Uncorrected Concentration,Scaling Factor,Averaged Scaling Factor,Corrected Concentration
0,A10-1,A10-1,A10-1,A10-1,A10-1,A10-1,0,,,
1,Peak#,R.time,I.time,F.Time,Area,Peak_ID,0,,,
2,3.495,3.451,3.579,1478,431,C3,1.12788358332,0.0225576716665,,
3,NaN,NaN,NaN,NaN,1e-09,C4,4.09286479424e-12,,155.722678962,2.6283036109528785e-14
4,12.099,11.987,12.107,28972122,4235909,C5,15571.1400126,311.422800253,,
5,NaN,NaN,NaN,NaN,1e-09,C6,2.43108269688e-12,,156.418169267,1.5542201448022407e-14
6,16.101,16.043,16.315,125724,34518,C7,70.6769140782,1.41353828156,,
7,17.482,17.421,17.61,1631,298,C8,0.572577651064,,1.48111926506,0.3865844328480529
8,18.511,18.453,18.71,134520,43532,C9,77.435012428,1.54870024856,,
9,NaN,NaN,NaN,NaN,1e-09,C10,1.79891239538e-12,,1.72480985288,1.0429627314435247e-12
10,20.498,20.434,20.702,139625,54277,C11,95.0459728596,1.90091945719,,
11,NaN,NaN,NaN,NaN,1e-09,C12,1.70386390898e-12,,1.96763684145,8.659443008445244e-13
12,22.272,22.212,22.404,139793,61143,C13,101.717711285,2.0343542257,,
13,NaN,NaN,NaN,NaN,1e-09,C14,1.67394357932e-12,,2.1011991731,7.966610689507985e-13
14,23.899,23.831,24.096,139603,65079,C15,108.402206025,2.16804412049,,
15,NaN,NaN,NaN,NaN,1e-09,C16,1.81645631004e-12,,2.52006025953,7.207987599357611e-13
16,25.404,25.358,25.495,153637,74666,C17,143.603819929,2.87207639857,,
17,A10-2,A10-2,A10-2,A10-2,A10-2,A10-2,0,,,
18,Peak#,R.time,I.time,F.Time,Area,Peak_ID,0,,,
19,3.496,3.451,3.575,1011,341,C3,0.892362649451,0.017847252989,,
20,NaN,NaN,NaN,NaN,1e-09,C4,4.09286479424e-12,,153.725734027,2.6624460895504814e-14
21,12.09,12.023,12.103,19575456,4181649,C5,15371.6810401,307.433620801,,
22,NaN,NaN,NaN,NaN,1e-09,C6,2.43108269688e-12,,154.416740765,1.574364725509779e-14
23,16.097,16.04,16.305,124189,34184,C7,69.9930364114,1.39986072823,,
24,17.479,17.423,17.554,1211,316,C8,0.60716287831,,1.36687614101,0.44419743683723345
25,18.503,18.438,18.804,114890,37494,C9,66.6945776894,1.33389155379,,
26,NaN,NaN,NaN,NaN,1e-09,C10,1.79891239538e-12,,1.44735346827,1.2428977681112346e-12
27,20.493,20.422,20.688,118143,44566,C11,78.0407691372,1.56081538274,,
28,NaN,NaN,NaN,NaN,1e-09,C12,1.70386390898e-12,,1.62069383975,1.0513175697936412e-12
29,22.271,22.194,22.558,117971,50510,C13,84.0286148374,1.68057229675,,
...,...,...,...,...,...,...,...,...,...,...
786,12.23,12.195,12.241,12475759,4665747,C5,17151.2182628,343.024365257,,
787,14.538,14.48,14.818,80018,19227,C6,46.7424270129,,172.195282231,0.2714501025079068
788,16.111,16.05,16.322,122462,33362,C7,68.3099602374,1.36619920475,,
789,17.394,17.34,17.594,130134,39711,C8,76.3007755081,,1.42498650473,53.54491095517042
790,18.511,18.447,18.987,127692,41707,C9,74.1886902356,1.48377380471,,
791,19.539,19.461,19.733,126261,43632,C10,78.4901456351,,1.53900035457,51.00073265228524
792,20.501,20.383,20.854,126972,45520,C11,79.7113452212,1.59422690442,,
793,21.412,21.328,21.575,136520,51823,C12,88.2993393552,,1.63710015195,53.93643098136915
794,22.28,22.197,22.448,126729,50492,C13,83.9986699737,1.67997339947,,
795,23.112,23.012,23.256,137694,57820,C14,96.7874177561,,1.74887687502,55.34261395899689
796,23.909,23.825,24.128,125250,54565,C15,90.8890175285,1.81778035057,,
797,24.676,24.595,24.782,126943,58732,C16,106.684112001,,2.14244518059,49.795492070316186
798,25.415,25.349,25.512,135737,64138,C17,123.35550053,2.4671100106,,
799,Rec-3,Rec-3,Rec-3,Rec-3,Rec-3,Rec-3,0,,,
800,Peak#,R.time,I.time,F.Time,Area,Peak_ID,0,,,
801,NaN,NaN,NaN,NaN,1e-09,C3,2.61689926525e-12,5.2337985305e-14,,
802,6.709,6.632,6.892,5150,1023,C4,4.1870006845,,156.0624935,0.026829000297208905
803,12.115,12.034,12.12,21378455,4245460,C5,15606.24935,312.124987001,,
804,14.543,14.484,14.82,76944,18493,C6,44.9580123134,,156.740638061,0.2868306067246122
805,16.112,16.054,16.335,121466,33120,C7,67.8144560597,1.35628912119,,
806,17.395,17.34,17.608,139540,42475,C8,81.6115292918,,1.49322935787,54.65438304022983
807,18.512,18.452,19.155,142603,45822,C9,81.508479727,1.63016959454,,
808,19.541,19.462,19.752,137777,47395,C10,85.2594529789,,1.73122241764,49.24812208414034
809,20.503,20.384,20.756,142759,52317,C11,91.6137620373,1.83227524075,,
810,21.413,21.328,21.587,145021,56998,C12,97.1168350841,,1.91265277725,50.775988323346084
811,22.281,22.191,22.548,144566,59901,C13,99.6515156875,1.99303031375,,
812,23.112,23.016,23.324,146437,63535,C14,106.354005312,,2.07472391792,51.26176277891502
813,23.909,23.823,24.127,144804,64730,C15,107.820876104,2.15641752208,,
814,24.676,24.592,24.791,139305,64672,C16,117.473862483,,2.52624824386,46.50131386257725
815,25.415,25.352,25.515,157400,75290,C17,144.803948282,2.89607896564,,

In [20]:
# Calculates and creates a sheet with corrected concentration data
# file         - file name
# sheet        - sheet with data organized by sample with peak areas and chain lengths identified already
# area_col     - column number of peak area data (1st column is column 0, 2nd column is column 1, etc.)
# chain_col    - column number of chain indentification data (1st column is column 0, 2nd column is column 1, etc.)
# scale        - dictionary of scale factors to turn area data into concentration data
# int_std_conc - dictionary of internal standard concentrations

def getData (file, sheet_name, area_col, chain_col, scale, int_std_conc, saveAs):
    col = [area_col, chain_col]
    wb = openpyxl.load_workbook(file)
    sheet = wb[sheet_name]
    orig = pd.read_excel(file, sheet_name=sheet_name, header=None)
    df = pd.read_excel(file, sheet_name=sheet_name, usecols = col, header=None)
    
    #add 4 empty columns
    df['Pfleger'] = ""
    df['Lab'] = ""
    df['For'] = ""
    df['Life'] = ""
    
    dfList = df.values.tolist()
    # Calculate
    for row in range(len(dfList)):
        chain = dfList[row][1]
        area = dfList[row][0]
        #Calculate Uncorrected Concentration
        if isinstance(area,str) or math.isnan(area):
            if chain != chain:
                dfList[row][2] = ""
            else:
                dfList[row][2] = 0
        else:
            if isinstance(area,float) or isinstance(area,int):
                dfList[row][2] = area/scale.get(chain)
        #Calculate Scaling Factor
        if (isinstance(area,float) or isinstance(area,int)) and dfList[row][2] != "" and int(chain[len(chain)-1])%2 == 1:
            dfList[row][3] = dfList[row][2]/int_std_conc[chain]
       
    #Calculate Averaged Scaling Factors and Corrected Concentrations
    for row in range(len(dfList)):
        chain = dfList[row][1]
        area = dfList[row][0]
        if (isinstance(area,float) or isinstance(area,int)) and dfList[row][2] != "" and int(chain[len(chain)-1])%2 == 0:
            flanking = np.array([dfList[row-1][3], dfList[row+1][3] if row+1<len(dfList) else dfList[row-1][3]])
            if flanking[0]=="":
                dfList[row][4] = flanking[1]
            elif flanking[1]=="":
                dfList[row][4] = flanking[0]
            else:
                dfList[row][4] = flanking.mean()
            uncorrected = float(dfList[row][2])
            avgscalefactor = float(dfList[row][4])
            dfList[row][5] = uncorrected/avgscalefactor
    
    #modify data type to allow python to write to excel
    dfList = np.array(dfList)
    concDataDict = {'Uncorrected Concentration' :dfList[:,2].tolist(), 
                    'Scaling Factor':dfList[:,3].tolist(), 
                    'Averaged Scaling Factor':dfList[:,4].tolist(), 
                    'Corrected Concentration':dfList[:,5].tolist()}
    order = ['Uncorrected Concentration','Scaling Factor','Averaged Scaling Factor','Corrected Concentration']
    concData = pd.DataFrame(concDataDict, columns = order)
    excelData = pd.concat([orig, concData], axis = 1)
    
    #write to the excel file
    writer = pd.ExcelWriter(file, engine = 'openpyxl')
    writer.book = wb
    excelData.to_excel(writer, sheet_name = "Corrected Concentration", index = False, startrow = 0, startcol = 0)
    wb.save(filename = saveAs)
    return excelData