In [130]:
import pandas as pd
import numpy as np
#from pandas import ExcelWriter
#from pandas import ExcelFile
#from scipy import stats
import matplotlib.pyplot as plt
import math
import xlwt
import openpyxl

In [131]:
wb = openpyxl.load_workbook('GCData-JGI_ACRs.xlsx')
sheet1 = ''
sheet1 = wb['John_Code']
sheet2 = ''
sheet2 = wb['Peak_ID']

In [132]:
df = pd.read_excel('GCData-JGI_ACRs.xlsx', sheet_name = 'John_Code', header = None)


#Preparing list of strings called Vial_names where each element is the name of a sample

Vial_names = []
Standard_names = ['FAOH-2000', 'FAOH-1000', 'FAOH-500', 'FAOH-100', 'FAOH-50', 'FAOH-10']
Sample_names = ['A10','A12', 'B12', 'C10','C11','C12','D10','E11','H9','H10','H12','MaACR','Neg','Rec']

for x in Sample_names:
    vial1 = x + '-1'
    Vial_names.append(vial1)
    vial2 = x + '-2'
    Vial_names.append(vial2)
    vial3 = x + '-3'
    Vial_names.append(vial3)
    
for x in Standard_names:
    Vial_names.append(x)

In [133]:
df

          0       1       2       3          4          5
0     A10-1     NaN     NaN     NaN        NaN        NaN
1     Peak#  R.Time  I.Time  F.Time       Area     Height
2         1   1.116   1.014   1.161  752299769  380283177
3         2   1.188   1.161   1.236  146465422   95128216
4         3   1.253   1.236   2.293    3752271    2228260
...     ...     ...     ...     ...        ...        ...
5206     93  27.566  27.479  27.594       4336        620
5207     94  27.646  27.594  27.668       2500        648
5208     95  27.779  27.668  27.803       2725        261
5209     96  28.033  27.902  28.092       1171        195
5210     97  28.243   28.18  28.318       2007        736

[5211 rows x 6 columns]

In [134]:
# FAOH Retention Times (minutes on FatWax column w Stabilwax protocol)


C3 = 3.526
C4 = 6.7
C5 = 12.171
C6 = 14.53
C7 = 16.119
C8 = 17.407
C9 = 18.536
C10 = 19.567
C11 = 20.529
C12 = 21.44
C13 = 22.307
C14 = 23.138
C15 = 23.936
C16 = 24.702
C17 = 25.429

# Create a dictionary which can be updated by changing values above. The dictionary will be called in peak identification (next block)

RT_dict = {'C3': C3, 'C4': C4, 'C5': C5, 'C6': C6, 'C7': C7, 'C8': C8, 'C9': C9, 'C10': C10, 'C11': C11, 'C12': C12, 'C13': C13, 'C14': C14, 'C15': C15, 'C16': C16, 'C17': C17}

# Create list of analytes to make it easy to call dictionary in future
analytes = ['C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17']

In [135]:
# This block goes through the dataframe from the John_Code sheet and picks out sample names and relevant peaks.

num_rows = len(df)
row_name = list(range(0, num_rows))
txt_file_headers = ['Peak#', 'R.time', 'I.time', 'F.Time', 'Area', 'Height']

for i in row_name:                
    if i < num_rows+1: 
        # picks out each row in dataframe and truncates - would be more elegant to not have to use dataframe but whatever
        row_calling = df.loc[i,:]
        vals = row_calling.values.tolist()
        vals = vals[0:6]
        
        y = type(vals[0])
        
        if vals[0] in Vial_names:
            sample_of_interest = 'yes'
        
            # picks out sample names and adds to worksheet
            print(vals[0])
            heading = [vals[0],vals[0],vals[0],vals[0],vals[0],vals[0]]
            print(heading)
            sheet2.append(heading)
            sheet2.append(txt_file_headers)

        elif vals[0] != 'Peak#' and y == str:
            sample_of_interest = 'no'
            
                
        # picks out peaks
        x = type(vals[1])
        if x == float and sample_of_interest == 'yes':
            for a in analytes:
                upper_tolerance = RT_dict[a] + 0.09
                lower_tolerance = RT_dict[a] - 0.09
                if vals[1] < upper_tolerance and vals[1] > lower_tolerance:
                    #print(vals[1])
                    vals.append(a)
                    #print(vals)
                    sheet2.append(vals[1:])

A10-1
['A10-1', 'A10-1', 'A10-1', 'A10-1', 'A10-1', 'A10-1']
A10-2
['A10-2', 'A10-2', 'A10-2', 'A10-2', 'A10-2', 'A10-2']
A10-3
['A10-3', 'A10-3', 'A10-3', 'A10-3', 'A10-3', 'A10-3']
A12-1
['A12-1', 'A12-1', 'A12-1', 'A12-1', 'A12-1', 'A12-1']
A12-2
['A12-2', 'A12-2', 'A12-2', 'A12-2', 'A12-2', 'A12-2']
A12-3
['A12-3', 'A12-3', 'A12-3', 'A12-3', 'A12-3', 'A12-3']
B12-1
['B12-1', 'B12-1', 'B12-1', 'B12-1', 'B12-1', 'B12-1']
B12-2
['B12-2', 'B12-2', 'B12-2', 'B12-2', 'B12-2', 'B12-2']
B12-3
['B12-3', 'B12-3', 'B12-3', 'B12-3', 'B12-3', 'B12-3']
C10-1
['C10-1', 'C10-1', 'C10-1', 'C10-1', 'C10-1', 'C10-1']
C10-2
['C10-2', 'C10-2', 'C10-2', 'C10-2', 'C10-2', 'C10-2']
C10-3
['C10-3', 'C10-3', 'C10-3', 'C10-3', 'C10-3', 'C10-3']
C11-1
['C11-1', 'C11-1', 'C11-1', 'C11-1', 'C11-1', 'C11-1']
C11-2
['C11-2', 'C11-2', 'C11-2', 'C11-2', 'C11-2', 'C11-2']
C11-3
['C11-3', 'C11-3', 'C11-3', 'C11-3', 'C11-3', 'C11-3']
C12-1
['C12-1', 'C12-1', 'C12-1', 'C12-1', 'C12-1', 'C12-1']
C12-2
['C12-2', 'C12-2', 'C12-2', 'C12-2', 'C12-2', 'C12-2']
C12-3
['C12-3', 'C12-3', 'C12-3', 'C12-3', 'C12-3', 'C12-3']
D10-1
['D10-1', 'D10-1', 'D10-1', 'D10-1', 'D10-1', 'D10-1']
D10-2
['D10-2', 'D10-2', 'D10-2', 'D10-2', 'D10-2', 'D10-2']
D10-3
['D10-3', 'D10-3', 'D10-3', 'D10-3', 'D10-3', 'D10-3']
E11-1
['E11-1', 'E11-1', 'E11-1', 'E11-1', 'E11-1', 'E11-1']
E11-2
['E11-2', 'E11-2', 'E11-2', 'E11-2', 'E11-2', 'E11-2']
E11-3
['E11-3', 'E11-3', 'E11-3', 'E11-3', 'E11-3', 'E11-3']
FAOH-10
['FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10']
FAOH-100
['FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100']
FAOH-1000
['FAOH-1000', 'FAOH-1000', 'FAOH-1000', 'FAOH-1000', 'FAOH-1000', 'FAOH-1000']
FAOH-2000
['FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000']
FAOH-50
['FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50']
FAOH-500
['FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500']
H10-1
['H10-1', 'H10-1', 'H10-1', 'H10-1', 'H10-1', 'H10-1']
H10-2
['H10-2', 'H10-2', 'H10-2', 'H10-2', 'H10-2', 'H10-2']
H10-3
['H10-3', 'H10-3', 'H10-3', 'H10-3', 'H10-3', 'H10-3']
H12-1
['H12-1', 'H12-1', 'H12-1', 'H12-1', 'H12-1', 'H12-1']
H12-2
['H12-2', 'H12-2', 'H12-2', 'H12-2', 'H12-2', 'H12-2']
H12-3
['H12-3', 'H12-3', 'H12-3', 'H12-3', 'H12-3', 'H12-3']
H9-1
['H9-1', 'H9-1', 'H9-1', 'H9-1', 'H9-1', 'H9-1']
H9-2
['H9-2', 'H9-2', 'H9-2', 'H9-2', 'H9-2', 'H9-2']
H9-3
['H9-3', 'H9-3', 'H9-3', 'H9-3', 'H9-3', 'H9-3']
MaACR-1
['MaACR-1', 'MaACR-1', 'MaACR-1', 'MaACR-1', 'MaACR-1', 'MaACR-1']
MaACR-2
['MaACR-2', 'MaACR-2', 'MaACR-2', 'MaACR-2', 'MaACR-2', 'MaACR-2']
MaACR-3
['MaACR-3', 'MaACR-3', 'MaACR-3', 'MaACR-3', 'MaACR-3', 'MaACR-3']
Neg-1
['Neg-1', 'Neg-1', 'Neg-1', 'Neg-1', 'Neg-1', 'Neg-1']
Neg-2
['Neg-2', 'Neg-2', 'Neg-2', 'Neg-2', 'Neg-2', 'Neg-2']
Neg-3
['Neg-3', 'Neg-3', 'Neg-3', 'Neg-3', 'Neg-3', 'Neg-3']
Rec-1
['Rec-1', 'Rec-1', 'Rec-1', 'Rec-1', 'Rec-1', 'Rec-1']
Rec-2
['Rec-2', 'Rec-2', 'Rec-2', 'Rec-2', 'Rec-2', 'Rec-2']
Rec-3
['Rec-3', 'Rec-3', 'Rec-3', 'Rec-3', 'Rec-3', 'Rec-3']

In [136]:
wb.save('GCData-JGI_ACRs.xlsx')

In [137]:
#Now remove duplicate peaks from Peak_ID tab

In [143]:
wb = openpyxl.load_workbook('GCData-JGI_ACRs.xlsx')
sheet2 = ''
sheet2 = wb['Peak_ID']
sheet3 = ''
sheet3 = wb.create_sheet('Quantification w IS,ES')

In [144]:
ID  = 'blank'
Area = 'blank'
sheet3_list = []

for row in sheet2.iter_rows(min_row = 1, max_row = 5000, min_col = 1, max_col = 10, values_only = True): # iterates through a semi-arbitrary number of rows and only reports values, still a tuple
    
    if row[5] == ID: # If there is a duplicate label for a single peak, pick the peak with the larger area
        if row[3] > Area:
            sheet3_list.pop()
            sheet3_list.append(row)
        else:
            continue
            
    else:
        sheet3_list.append(row)

    
    if row[3] == None:
        break
    
    else:
        ID = row[5]
        Area = row[3]
    
    
    
for row in sheet3_list:
    sheet3.append(row)
    
#Notice that this code may not work as intended if there is a duplicate in the first row, however, since the first row will always be a sample name, it is fine.

In [145]:
wb.save('GCData-JGI_ACRs.xlsx')