In [17]:
import pandas as pd
import numpy as np
#from pandas import ExcelWriter
#from pandas import ExcelFile
#from scipy import stats
import matplotlib.pyplot as plt
import math
import xlwt
import openpyxl

In [18]:
wb = openpyxl.load_workbook('GCData_for_Ryan_w_FaOH_STD_Data.xlsx')
sheet1 = ''
sheet1 = wb['John_Code']
sheet2 = ''
wb.create_sheet('Peak_ID (3)')
sheet2 = wb['Peak_ID (3)']

In [19]:
df = pd.read_excel('GCData_for_Ryan_w_FaOH_STD_Data.xlsx', sheet_name = 'John_Code')


#Preparing list of strings called Vial_names where each element is the name of a sample

Vial_names = []
Standard_names = ['FAOH-10', 'FAOH-100', 'FAOH-2000', 'FAOH-50', 'FAOH-500']
Sample_names = ['CM24', 'CM32', 'I287A', 'rec', 'trc', 'vhb']

for x in Sample_names:
    vial1 = x + '-1'
    Vial_names.append(vial1)
    vial2 = x + '-2'
    Vial_names.append(vial2)
    vial3 = x + '-3'
    Vial_names.append(vial3)
    
for x in Standard_names:
    Vial_names.append(x)

In [20]:
df

      PeakNo  R.Time  I.Time  F.Time       Area     Height
0     CM24-1     NaN     NaN     NaN        NaN        NaN
1      Peak#  R.Time  I.Time  F.Time       Area     Height
2          1   1.397   1.298   1.792  514754671  157751223
3          2    1.58   1.554   1.662      74525      21862
4          3   1.766   1.704   1.792      64779      13638
5          4   2.274   1.792   3.253  646809919   50836518
6          5   2.488    2.45     2.6     212937     126536
7          6    2.91   2.889   2.996       1198        301
8          7   3.095   3.006   3.141      12368       6006
9          8   3.181   3.141   3.248       1368        353
10         9   3.325   3.253   3.379       1291        329
11        10   3.446   3.379   3.664     148050      36800
12        11   3.749   3.664   3.808       1853        448
13        12    3.85   3.813   3.911        597        110
14        13   3.925   3.911   3.953        435        193
15        14   3.987   3.953   4.037       4436       2232
16        15   4.135   4.037   4.172       1694        276
17        16   4.191   4.172   4.228        616        212
18        17   4.299   4.228   4.406       1766        313
19        18   4.487   4.406   4.574        929        181
20        19   4.644   4.574   4.686        460        119
21        20   4.872   4.788    4.97       2944        556
22        21   5.051    4.97   5.115       2076        396
23        22   5.189   5.115    5.25       3505       1455
24        23   5.685   5.577   5.708       1171        285
25        24   5.813   5.708   5.885       5313        936
26        25       6   5.885    6.45     173827      34612
27        26   6.702   6.594   6.772       4085       1104
28        27  10.158  10.052  10.491     187457      46729
29        28  12.437  12.376  12.605     189232      82739
...      ...     ...     ...     ...        ...        ...
1590      45   15.18  15.111  15.218        120         40
1591      46   15.27  15.218  15.321       1292        604
1592      47  15.382  15.321  15.405        692        196
1593      48  15.438  15.405   15.47        972        264
1594      49  15.506   15.47  15.545       6350       2792
1595      50   15.57  15.545  15.685       5720        937
1596      51  15.734  15.685   15.76       2373        563
1597      52  15.788   15.76  15.848       2959        580
1598      53  15.876  15.848  15.914       2241        582
1599      54  16.011  15.914  16.114       8204        775
1600      55  16.178  16.114   16.31      17901       4191
1601      56  16.344   16.31  16.422       8265       2244
1602      57  16.457  16.422  16.511       4232        851
1603      58  16.543  16.511  16.637       5756        941
1604      59    16.7  16.637   16.81       5975        622
1605      60  16.871   16.81  16.922       3367        552
1606      61  16.964  16.922  17.024       3959        977
1607      62  17.048  17.024   17.15       2607        433
1608      63  17.187   17.15  17.267       1458        275
1609      64  17.337  17.267  17.365        612        144
1610      65  17.408  17.365  17.458        702        150
1611      66  17.552  17.458  17.617        927        137
1612      67  17.673  17.631  17.762        146         32
1613      68   17.79  17.762   17.86        170         48
1614      69  17.915   17.86  18.004       7757       2442
1615      70  18.053  18.004  18.112        986        269
1616      71  18.319  18.196  18.574       5209        847
1617      72  18.674  18.574  18.844       1866        169
1618      73  19.635  19.568  19.726       1259        326
1619      74   20.55  20.459   20.66       1298        268

[1620 rows x 6 columns]

In [23]:
# This block goes through the dataframe from the John_Code sheet and picks out sample names and relevant peaks.

num_rows = len(df)
row_name = list(range(0, num_rows))

for i in row_name:                
    if i < num_rows+1: 
        # picks out each row in dataframe and truncates - would be more elegant to not have to use dataframe but whatever
        row_calling = df.loc[i,:]
        vals = row_calling.values.tolist()
        vals = vals[0:6]
        
        # picks out sample names and adds to worksheet
        for label in Vial_names:
            if vals[0] == label:
                print(vals[0])
                heading = [vals[0],vals[0],vals[0],vals[0],vals[0],vals[0]]
                print(heading)
                sheet2.append(heading)
                
        # picks out peaks
        x = type(vals[1])
        if x == float:
            for a in analytes:
                upper_tolerance = RT_dict[a] + 0.09
                lower_tolerance = RT_dict[a] - 0.09
                if vals[1] < upper_tolerance and vals[1] > lower_tolerance:
                    #print(vals[1])
                    vals.append(a)
                    #print(vals)
                    sheet2.append(vals[1:])

CM24-1
['CM24-1', 'CM24-1', 'CM24-1', 'CM24-1', 'CM24-1', 'CM24-1']
CM24-2
['CM24-2', 'CM24-2', 'CM24-2', 'CM24-2', 'CM24-2', 'CM24-2']
CM24-3
['CM24-3', 'CM24-3', 'CM24-3', 'CM24-3', 'CM24-3', 'CM24-3']
CM32-1
['CM32-1', 'CM32-1', 'CM32-1', 'CM32-1', 'CM32-1', 'CM32-1']
CM32-2
['CM32-2', 'CM32-2', 'CM32-2', 'CM32-2', 'CM32-2', 'CM32-2']
CM32-3
['CM32-3', 'CM32-3', 'CM32-3', 'CM32-3', 'CM32-3', 'CM32-3']
FAOH-10
['FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10', 'FAOH-10']
FAOH-100
['FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100', 'FAOH-100']
FAOH-2000
['FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000', 'FAOH-2000']
FAOH-50
['FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50', 'FAOH-50']
FAOH-500
['FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500', 'FAOH-500']
I287A-1
['I287A-1', 'I287A-1', 'I287A-1', 'I287A-1', 'I287A-1', 'I287A-1']
I287A-2
['I287A-2', 'I287A-2', 'I287A-2', 'I287A-2', 'I287A-2', 'I287A-2']
I287A-3
['I287A-3', 'I287A-3', 'I287A-3', 'I287A-3', 'I287A-3', 'I287A-3']
rec-1
['rec-1', 'rec-1', 'rec-1', 'rec-1', 'rec-1', 'rec-1']
rec-2
['rec-2', 'rec-2', 'rec-2', 'rec-2', 'rec-2', 'rec-2']
rec-3
['rec-3', 'rec-3', 'rec-3', 'rec-3', 'rec-3', 'rec-3']
trc-1
['trc-1', 'trc-1', 'trc-1', 'trc-1', 'trc-1', 'trc-1']
trc-2
['trc-2', 'trc-2', 'trc-2', 'trc-2', 'trc-2', 'trc-2']
trc-3
['trc-3', 'trc-3', 'trc-3', 'trc-3', 'trc-3', 'trc-3']
vhb-1
['vhb-1', 'vhb-1', 'vhb-1', 'vhb-1', 'vhb-1', 'vhb-1']
vhb-2
['vhb-2', 'vhb-2', 'vhb-2', 'vhb-2', 'vhb-2', 'vhb-2']
vhb-3
['vhb-3', 'vhb-3', 'vhb-3', 'vhb-3', 'vhb-3', 'vhb-3']

In [25]:
# FAOH Retention Times (minutes on DB-Fatwax column)

C4 = 1.7
C5 = 2.12
C6 = 2.6
C7 = 3.45
C8 = 4.65
C9 = 6.07
C10 = 7.95
C11 = 10.2
C12 = 11.55
C13 = 12.5
C14 = 13.2
C15 = 13.86
C16 = 14.4
# Create a dictionary which can be updated by changing values above. The dictionary will be called in peak identification (next block)
RT_dict = {'C4' : C4, 'C5' : C5, 'C6' : C6, 'C7': C7, 'C8': C8, 'C9': C9, 'C10': C10, 'C11': C11, 'C12': C12, 'C13': C13, 'C14': C14, 'C15': C15, 'C16': C16}
# Create list of analytes to make it easy to call dictionary in future
analytes = ['C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16']

In [26]:
wb.save('GCData_for_Ryan_w_FaOH_STD_Data.xlsx')