In [34]:
import pandas as pd
import numpy as np
#from pandas import ExcelWriter
#from pandas import ExcelFile
#from scipy import stats
import matplotlib.pyplot as plt
import math
import xlwt
import openpyxl

In [35]:
wb = openpyxl.load_workbook('GCData.xlsx')
sheet1 = wb['John_Code']
sheet2 = wb['Peak_ID']

In [36]:
df = pd.read_excel('GCData.xlsx', sheet_name = 'John_Code')


#Preparing list of strings called Vial_names where each element is the name of a sample

Vial_names = []
Standard_names = ['1g_oddfames', '500mg_oddfames', '100mg_oddfames', '25mg_oddfames', 'FAME1000', 'FAME500', 'FAME100', 'FAME25']
Sample_names = ['Sc1','H204A', 'WT', 'Rec']

for x in Sample_names:
    vial1 = x + '-1'
    Vial_names.append(vial1)
    vial2 = x + '-2'
    Vial_names.append(vial2)
    vial3 = x + '-3'
    Vial_names.append(vial3)
    
for x in Standard_names:
    Vial_names.append(x)

In [37]:
df

       Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
0     1g_oddfames        NaN        NaN        NaN        NaN        NaN
1           Peak#     R.Time     I.Time     F.Time       Area     Height
2               1      1.361      1.288      1.382       2083       1122
3               2      1.413      1.382      1.489       5507       1704
4               3      1.521      1.489      2.287  695024823  120059358
...           ...        ...        ...        ...        ...        ...
2054          110     21.594     21.518     21.681       8717       1938
2055          111     21.733     21.681     21.793       1517        312
2056          112     21.845     21.793     21.943       1014        211
2057          113     22.071     21.947     22.255       3670        473
2058          114     22.453     22.395     22.479       1289        473

[2059 rows x 6 columns]

In [38]:
# FAME Retention Times (minutes on DB-Fatwax column)

C7 = 2.35
C8 = 3.06
C9 = 3.92
C10 = 5.29
C11 = 6.79
C12 = 9.22
C13 = 10.86
C14 = 12.05
C15 = 12.86
C16 = 13.62
C17 = 14.18

# Create a dictionary which can be updated by changing values above. The dictionary will be called in peak identification (next block)

RT_dict = {'C7': C7, 'C8': C8, 'C9': C9, 'C10': C10, 'C11': C11, 'C12': C12, 'C13': C13, 'C14': C14, 'C15': C15, 'C16': C16, 'C17': C17}

# Create list of analytes to make it easy to call dictionary in future
analytes = ['C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17']

In [39]:
# This block goes through the dataframe from the John_Code sheet and picks out sample names and relevant peaks.

row_name = list(range(0,2059))

for i in row_name:
    if i < 2060: 
        # picks out each row in dataframe and truncates - would be more elegant to not have to use dataframe but whatever
        row_calling = df.loc[i,:]
        vals = row_calling.values.tolist()
        vals = vals[0:6]
        
        # picks out sample names and adds to worksheet
        for label in Vial_names:
            if vals[0] == label:
                print(vals[0])
                sheet2.append(vals)
                
        # picks out peaks
        x = type(vals[1])
        if x == float:
            for a in analytes:
                upper_tolerance = RT_dict[a] + 0.09
                lower_tolerance = RT_dict[a] - 0.09
                if vals[1] < upper_tolerance and vals[1] > lower_tolerance:
                    #print(vals[1])
                    vals.append(a)
                    #print(vals)
                    sheet2.append(vals[1:])

1g_oddfames
100mg_oddfames
25mg_oddfames
500mg_oddfames
FAME100
FAME1000
FAME25
FAME500
H204A-1
H204A-2
H204A-3
Rec-1
Rec-2
Rec-3
Sc1-1
Sc1-2
Sc1-3
WT-1
WT-2
WT-3

In [ ]:
wb.save('GCData.xlsx')