In [13]:
import pandas as pd
import numpy as np
from numpy import array
import matplotlib.pyplot as plt
import math
import openpyxl
from statistics import *

In [14]:
#This code will parse through the Peak_ID worksheet and generate another worksheet in the same file called "External_STD"
#with concentration and peak area data for C7, C8, ..., C17 arranged like so:
#
# Chain Length | Conc (mg/L) | Peak Area | Conc (mg/L) | Peak Area | Conc (mg/L) | Peak Area | Conc (mg/L) | Peak Area
# _____________________________________________________________________________________________________________________
#      C7      |    1000     |     #     |     500     |     #     |     100     |     #     |     25      |     #
#      C8      |    1000     |     #     |     500     |     #     |     100     |     #     |     25      |     #
#      ...     |    1000     |     #     |     500     |     #     |     100     |     #     |     25      |     #
#      C17     |    1000     |     #     |     500     |     #     |     100     |     #     |     25      |     #
#


###Important note: The standard data entries need to be included in the dataframe such that they are not the first nor the last entry. The loop throws an index out of range error otherwise.

In [15]:
def getExternalStdData(file, sheet, area_col, chain_col, standards_used, alc_acid_ID, saveAs):
    col = [area_col, chain_col]
    wb = openpyxl.load_workbook(file)
    sheet_name = wb[sheet]
    #create dataframe from relevant columns only
    df = pd.read_excel(file, sheet_name=sheet, usecols = col, header = None)
    print(df)
    #convert dataframe to array to allow array traversals
    dfList = df.values.tolist()
    print(dfList)
    #Master_dict will hold area and concentration data 
    Master_dict = standards_used

    # creates list of external standard title indicies (location of titles)
    alc_acid_indicies = []
    for i in range(len(dfList)):
        name = dfList[i][1]
        if name[0:name.find('-')] == alc_acid_ID:
            alc_acid_indicies.append(i)
    
    conc_array = []
    titleTypes = ['Peak#', 'R.Time', 'I.Time', 'F.Time', 'Area', 'Height']
    # start adding to master matrix here using indicies of titles
    for i in alc_acid_indicies:
        #find the position right before the start of a new set of data as indicated by a string
        endindex = i
        for k in range(len(dfList[i:len(dfList)])):
            endindex+=1
            print(endindex)
            testVar = dfList[endindex][0]
            print(testVar)
            if(isinstance(testVar,str) and testVar not in titleTypes):
                break
        #parse title to find concentration (gets the number after '-' in the title) and add to conc_array and sort
        conc = dfList[i][1][dfList[i][1].find('-')+1:len(dfList[i][1])]
        conc_array.append(int(conc))
        conc_array.sort()
        #for each chain, add the concentration and area data to the Master dictionary
        for j in range(endindex-i):
            if(isinstance(dfList[i+j][0], int)):
                conc_and_area = [conc, dfList[i+j][0]]
                Master_dict[dfList[i+j][1]].append(conc_and_area)

    #create master matrix holding arrays of area values
    num_conc, num_chain = len(conc_array), len(Master_dict);
    Master = [[0 for x in range(num_conc*2+1)] for y in range(num_chain+1)]
    
    #populate column titles
    Master[0][0] = 'Chain Length'
    for i in range(1, num_conc*2+1):
        if i%2==0:
            Master[0][i] = 'Peak Area'
        else:
            Master[0][i] = 'Conc (mg/L)'
    
    #create matrix with desired layout as seen in Cell 2
    chain_iterator = 1
    for chain in Master_dict:
        conc_iterator = 1
        #label first column with chain
        Master[chain_iterator][0] = chain
        for conc in conc_array:
            area = []
            #search for correct area data
            for pair in Master_dict[chain]:
                if int(pair[0]) == conc:
                    area.append(pair[1])
                    break
            #this accounts for double-counting areas (only picks the largest one)
            area.sort(reverse = True)
            #this accounts for no area data
            if len(area) == 0:
                area = ['']
            #add to the master matrix
            Master[chain_iterator][conc_iterator] = conc
            conc_iterator+=1
            Master[chain_iterator][conc_iterator] = area[0]
            conc_iterator+=1
        chain_iterator+=1
        
    excelData = pd.DataFrame(data=Master, index=None)
    #set first row as header for aesthetics
    new_header = excelData.iloc[0]
    excelData = excelData[1:]
    excelData.columns = new_header
    #write to the excel file
    writer = pd.ExcelWriter(file, engine = 'openpyxl')
    writer.book = wb
    excelData.to_excel(writer, sheet_name = "EXT_STD", index = False)
    wb.save(filename = saveAs)
    return excelData

In [16]:
#7/27/2020 - Mike, I changed all 'sheet_name' to 'sheetname' because 'sheet_name' was causing problems on my end,
# so you will need to change it back later if it's causing issues on your end.

file = 'GCData_C10TE_FAME.xlsx' #file name

# 11-19-2020 had to manually mess with the external standard data in the Quantification w IS,ES tab. Needed to delete lines with 12_1, 14_1, 16_1

sheet = 'Quantification w IS,ES' #name of sheet containing area and chain identification data
area_col = 3 #column number of area data indexed starting at 0 i.e. column A is 0, column B is 1, etc.
chain_col = 5 #column number of chain identification indexed starting at 0 i.e. column A is 0, column B is 1, etc.
standards_used = {'C7':[],'C8':[], 'C9':[], 'C10':[], 'C11':[], 'C12':[],
                  'C13':[], 'C14':[], 'C15':[], 'C16':[], 'C17':[], 'C18_1':[], 'C18':[]} #external standards used. Add or remove chains.
alc_acid_ID = 'FAME' #FAOH or FAME, assumes the format: <FAME/FAOH>-<Concentration> e.g. FAOH-100 or FAME-2000
saveAs = 'GCData_C10TE_FAME.xlsx' #save as new/old file name
getExternalStdData(file, sheet, area_col, chain_col, standards_used, alc_acid_ID, saveAs)

             3          5
0    ChFatB2-1  ChFatB2-1
1       F.Time    Peak_ID
2        67401         C7
3       185926         C8
4       238545         C9
..         ...        ...
287      27043      C16_1
288      37736        C16
289      64212        C17
290      69550      C18_1
291       1533        C18

[292 rows x 2 columns]
[['ChFatB2-1', 'ChFatB2-1'], ['F.Time', 'Peak_ID'], [67401, 'C7'], [185926, 'C8'], [238545, 'C9'], [91782, 'C10'], [309440, 'C11'], [4813, 'C12_1'], [5077, 'C12'], [349098, 'C13'], [2180, 'C14_1'], [11714, 'C14'], [58812, 'C15'], [21594, 'C16_1'], [99189, 'C16'], [62927, 'C17'], [31499, 'C18_1'], [3538, 'C18'], ['ChFatB2-2', 'ChFatB2-2'], ['F.Time', 'Peak_ID'], [91168, 'C7'], [197289, 'C8'], [279760, 'C9'], [95450, 'C10'], [367492, 'C11'], [5161, 'C12_1'], [5107, 'C12'], [415416, 'C13'], [2383, 'C14_1'], [12809, 'C14'], [69850, 'C15'], [24043, 'C16_1'], [113565, 'C16'], [74539, 'C17'], [38089, 'C18_1'], [4143, 'C18'], ['ChFatB2-3', 'ChFatB2-3'], ['F.Time', 'Peak_ID'], [93335, 'C7'], [185443, 'C8'], [265457, 'C9'], [89204, 'C10'], [343655, 'C11'], [4871, 'C12_1'], [4898, 'C12'], [385293, 'C13'], [2179, 'C14_1'], [11923, 'C14'], [64574, 'C15'], [22792, 'C16_1'], [114947, 'C16'], [68852, 'C17'], [54062, 'C18_1'], [4543, 'C18'], ['Cl2FatB2-1', 'Cl2FatB2-1'], ['F.Time', 'Peak_ID'], [119499, 'C7'], [12089, 'C8'], [262960, 'C9'], [168818, 'C10'], [335430, 'C11'], [21225, 'C12_1'], [30565, 'C12'], [372929, 'C13'], [5277, 'C14_1'], [76939, 'C14'], [62890, 'C15'], [39718, 'C16_1'], [199979, 'C16'], [66575, 'C17'], [46564, 'C18_1'], [2582, 'C18'], ['Cl2FatB2-2', 'Cl2FatB2-2'], ['F.Time', 'Peak_ID'], [143646, 'C7'], [12711, 'C8'], [270661, 'C9'], [170482, 'C10'], [320787, 'C11'], [21015, 'C12_1'], [29809, 'C12'], [350381, 'C13'], [5140, 'C14_1'], [73604, 'C14'], [59324, 'C15'], [39413, 'C16_1'], [193072, 'C16'], [63083, 'C17'], [50318, 'C18_1'], [2486, 'C18'], ['Cl2FatB2-3', 'Cl2FatB2-3'], ['F.Time', 'Peak_ID'], [105636, 'C7'], [11905, 'C8'], [259184, 'C9'], [176132, 'C10'], [337567, 'C11'], [22654, 'C12_1'], [32369, 'C12'], [383463, 'C13'], [5717, 'C14_1'], [82646, 'C14'], [65696, 'C15'], [44351, 'C16_1'], [216053, 'C16'], [70022, 'C17'], [56400, 'C18_1'], [2593, 'C18'], ['ClFatB3-1', 'ClFatB3-1'], ['F.Time', 'Peak_ID'], [82374, 'C7'], [7508, 'C8'], [229192, 'C9'], [108293, 'C10'], [253929, 'C11'], [12940, 'C12_1'], [19044, 'C12'], [256870, 'C13'], [2985, 'C14_1'], [42031, 'C14'], [41821, 'C15'], [19930, 'C16_1'], [121965, 'C16'], [42610, 'C17'], [17889, 'C18_1'], [1775, 'C18'], ['ClFatB3-2', 'ClFatB3-2'], ['F.Time', 'Peak_ID'], [102173, 'C7'], [7281, 'C8'], [241773, 'C9'], [95142, 'C10'], [283579, 'C11'], [12125, 'C12_1'], [19387, 'C12'], [306625, 'C13'], [3148, 'C14_1'], [47521, 'C14'], [51660, 'C15'], [23699, 'C16_1'], [153219, 'C16'], [54436, 'C17'], [29122, 'C18_1'], [2364, 'C18'], ['ClFatB3-3', 'ClFatB3-3'], ['F.Time', 'Peak_ID'], [116049, 'C7'], [7630, 'C8'], [268462, 'C9'], [105347, 'C10'], [337341, 'C11'], [13374, 'C12_1'], [22503, 'C12'], [379504, 'C13'], [3631, 'C14_1'], [52247, 'C14'], [64839, 'C15'], [26628, 'C16_1'], [174418, 'C16'], [69063, 'C17'], [32282, 'C18_1'], [2795, 'C18'], ['FAME-100', 'FAME-100'], ['F.Time', 'Peak_ID'], [51809, 'C7'], [52785, 'C8'], [58931, 'C9'], [60824, 'C10'], [62513, 'C11'], [63446, 'C12'], [68818, 'C13'], [94286, 'C14'], [99450, 'C15'], [101563, 'C16'], [101448, 'C17'], [93638, 'C18_1'], [53111, 'C18'], ['FAME-1000', 'FAME-1000'], ['F.Time', 'Peak_ID'], [710225, 'C7'], [720618, 'C8'], [802022, 'C9'], [823777, 'C10'], [846202, 'C11'], [857547, 'C12'], [929902, 'C13'], [1079785, 'C14'], [1135468, 'C15'], [1160369, 'C16'], [1160181, 'C17'], [1075268, 'C18_1'], [605657, 'C18'], ['FAME-25', 'FAME-25'], ['F.Time', 'Peak_ID'], [13404, 'C7'], [13540, 'C8'], [14982, 'C9'], [15422, 'C10'], [15719, 'C11'], [15792, 'C12'], [17259, 'C13'], [21031, 'C14'], [22018, 'C15'], [22308, 'C16'], [41131, 'C17'], [20350, 'C18_1'], [11780, 'C18'], ['FAME-50', 'FAME-50'], ['F.Time', 'Peak_ID'], [35344, 'C7'], [35831, 'C8'], [40111, 'C9'], [41177, 'C10'], [42206, 'C11'], [42769, 'C12'], [46322, 'C13'], [44228, 'C14'], [46724, 'C15'], [47587, 'C16'], [47469, 'C17'], [43822, 'C18_1'], [25233, 'C18'], ['FAME-500', 'FAME-500'], ['F.Time', 'Peak_ID'], [371446, 'C7'], [379696, 'C8'], [425129, 'C9'], [438411, 'C10'], [452843, 'C11'], [461495, 'C12'], [503722, 'C13'], [520167, 'C14'], [546896, 'C15'], [558591, 'C16'], [557713, 'C17'], [515456, 'C18_1'], [289540, 'C18'], [64027, 'C18'], ['WT-1', 'WT-1'], ['F.Time', 'Peak_ID'], [73719, 'C7'], [4724, 'C8'], [260072, 'C9'], [14484, 'C10'], [349305, 'C11'], [166521, 'C12_1'], [807683, 'C12'], [397543, 'C13'], [132005, 'C14_1'], [45673, 'C14'], [66832, 'C15'], [29354, 'C16_1'], [42183, 'C16'], [71912, 'C17'], [74429, 'C18_1'], [1853, 'C18'], ['WT-2', 'WT-2'], ['F.Time', 'Peak_ID'], [106496, 'C7'], [4004, 'C8'], [259018, 'C9'], [12654, 'C10'], [346932, 'C11'], [157856, 'C12_1'], [688375, 'C12'], [386248, 'C13'], [112252, 'C14_1'], [34691, 'C14'], [64284, 'C15'], [17683, 'C16_1'], [28667, 'C16'], [68780, 'C17'], [45469, 'C18_1'], [1294, 'C18'], ['WT-3', 'WT-3'], ['F.Time', 'Peak_ID'], [131656, 'C7'], [3740, 'C8'], [252251, 'C9'], [13460, 'C10'], [328021, 'C11'], [152198, 'C12_1'], [744045, 'C12'], [357723, 'C13'], [121650, 'C14_1'], [41992, 'C14'], [59759, 'C15'], [27043, 'C16_1'], [37736, 'C16'], [64212, 'C17'], [69550, 'C18_1'], [1533, 'C18']]
163
F.Time
164
51809
165
52785
166
58931
167
60824
168
62513
169
63446
170
68818
171
94286
172
99450
173
101563
174
101448
175
93638
176
53111
177
FAME-1000
178
F.Time
179
710225
180
720618
181
802022
182
823777
183
846202
184
857547
185
929902
186
1079785
187
1135468
188
1160369
189
1160181
190
1075268
191
605657
192
FAME-25
193
F.Time
194
13404
195
13540
196
14982
197
15422
198
15719
199
15792
200
17259
201
21031
202
22018
203
22308
204
41131
205
20350
206
11780
207
FAME-50
208
F.Time
209
35344
210
35831
211
40111
212
41177
213
42206
214
42769
215
46322
216
44228
217
46724
218
47587
219
47469
220
43822
221
25233
222
FAME-500
223
F.Time
224
371446
225
379696
226
425129
227
438411
228
452843
229
461495
230
503722
231
520167
232
546896
233
558591
234
557713
235
515456
236
289540
237
64027
238
WT-1

,Chain Length,Conc (mg/L),Peak Area,Conc (mg/L),Peak Area,Conc (mg/L),Peak Area,Conc (mg/L),Peak Area,Conc (mg/L),Peak Area
1,C7,25,13404,50,35344,100,51809,500,371446,1000,710225
2,C8,25,13540,50,35831,100,52785,500,379696,1000,720618
3,C9,25,14982,50,40111,100,58931,500,425129,1000,802022
4,C10,25,15422,50,41177,100,60824,500,438411,1000,823777
5,C11,25,15719,50,42206,100,62513,500,452843,1000,846202
6,C12,25,15792,50,42769,100,63446,500,461495,1000,857547
7,C13,25,17259,50,46322,100,68818,500,503722,1000,929902
8,C14,25,21031,50,44228,100,94286,500,520167,1000,1079785
9,C15,25,22018,50,46724,100,99450,500,546896,1000,1135468
10,C16,25,22308,50,47587,100,101563,500,558591,1000,1160369
11,C17,25,41131,50,47469,100,101448,500,557713,1000,1160181
12,C18_1,25,20350,50,43822,100,93638,500,515456,1000,1075268
13,C18,25,11780,50,25233,100,53111,500,289540,1000,605657