In [15]:
import pandas as pd
import numpy as np
from pandas import ExcelWriter
from pandas import ExcelFile
from scipy import stats
import statistics
import matplotlib.pyplot as plt
import math

In [16]:
df = pd.read_excel('GCData.xlsx', sheet_name = 'Sheet1')

In [17]:
df

,PeakNo,R.Time,I.Time,F.Time,Area,Height,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,1g_oddfames,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Peak#,R.Time,I.Time,F.Time,Area,Height,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1.361,1.288,1.382,2083,1122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,1.413,1.382,1.489,5507,1704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,1.521,1.489,2.287,695024823,120059358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4,2.359,2.287,3.113,1582248,469064,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5,2.981,2.917,3.099,17895,5644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6,3.926,3.832,4.228,1808591,623172,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7,5.166,5.101,5.292,5776,1938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,8,6.797,6.641,6.944,2066882,570294,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,9,7.409,7.332,7.5,1433,301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10,7.562,7.5,7.658,10289,3370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,11,7.77,7.705,7.901,1109,275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,12,8.974,8.806,9.04,2171,397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,13,10.855,10.738,11.037,2369550,759086,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,14,11.233,11.182,11.28,3614,1902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,15,11.532,11.387,11.648,4497,1390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,16,11.942,11.905,11.98,1536,777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,17,12.03,11.98,12.063,2193,566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,18,12.203,12.063,12.264,9762,1416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,19,12.317,12.264,12.432,5757,1128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,20,12.451,12.432,12.53,1381,297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,21,12.859,12.745,12.955,2552762,1064512,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,22,13.009,12.955,13.053,1235,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,23,13.232,13.202,13.291,1155,645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,24,13.536,13.487,13.576,2248,1460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,25,13.709,13.585,13.753,3151,1850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,26,14.187,13.982,14.266,2048413,998337,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,27,14.384,14.266,14.43,10345,3409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,28,14.554,14.43,14.579,9560,1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,85,17.683,17.663,17.715,1996,769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027,86,17.764,17.715,17.822,9988,3926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,87,17.92,17.887,17.962,1632,764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2029,88,18.062,17.962,18.167,94136,13269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2030,89,18.186,18.167,18.312,43740,5836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2031,90,18.387,18.312,18.433,39948,6679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2032,91,18.486,18.433,18.583,62048,11755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2033,92,18.609,18.583,18.681,21193,3797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034,93,18.779,18.681,18.83,31027,3838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2035,94,18.971,18.83,19.035,44864,5123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2036,95,19.11,19.035,19.157,22058,3269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2037,96,19.189,19.157,19.213,9464,2858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038,97,19.267,19.213,19.348,27817,4313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039,98,19.367,19.348,19.451,16646,2862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2040,99,19.488,19.451,19.544,13346,2486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2041,100,19.588,19.544,19.689,19137,2454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2042,101,19.841,19.689,19.917,36387,4232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2043,102,19.941,19.917,20.048,16583,2467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2044,103,20.127,20.048,20.216,25508,4618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2045,104,20.352,20.216,20.468,28180,4604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2046,105,20.551,20.468,20.641,8455,1004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2047,106,20.673,20.641,20.715,2433,569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2048,107,20.783,20.715,20.851,6515,1076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,108,20.882,20.851,21.079,4864,710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2050,109,21.422,21.299,21.518,6435,1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2051,110,21.594,21.518,21.681,8717,1938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2052,111,21.733,21.681,21.793,1517,312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2053,112,21.845,21.793,21.943,1014,211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,113,22.071,21.947,22.255,3670,473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2055,114,22.453,22.395,22.479,1289,473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
Sample_names = ['1g_oddfames', '100mg_oddfames','poop']

data_block = []

row_name = list(range(0,2056))

for i in row_name:
    if i < 100:
        row_calling = df.loc[i,:]
        vals = row_calling.values.tolist()
        vals = vals[0:6]
        for label in Sample_names:
            if vals[0] == label:
                data_block.append(vals)
                    
        #val = df.loc[df.PeakNo == row_name]
        #short_list = val.iloc[0:0,0:5]
        #print(short_list)

['1g_oddfames', nan, nan, nan, nan, nan]